/* auto-generated by OHOS-RS */
/* eslint-disable */
import { NodeContent } from "@kit.ArkUI";

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback;
  windowStageEventCallback: WindowStageEventCallback;
  keyboardEventCallback: KeyboardCallback;
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void;
  onMemoryLevel: (arg: number) => void;
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void;
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void;
  onWindowStageDestroy: () => void;
  onAbilityCreate: () => void;
  onAbilityDestroy: () => void;
  onAbilitySaveState: () => void;
  onAbilityRestoreState: () => void;
  onWindowStageEvent: (arg: number) => void;
  onWindowSizeChange: (arg: object) => void;
  onWindowRectChange: (arg: object) => void;
}

export declare function init(): ApplicationLifecycle;

export declare function registerClipboardCallbacks(
  readClipboard: () => unknown,
  writeClipboard: (arg: string) => unknown,
): void;

export declare function render(helper: object, slot: NodeContent): void;

export declare function setPreferencesPath(preferencesPath: string): void;
